[package]
name = "planets"
version = "0.1.0"
authors = ["Ashley Blewer <ashley.blewer@gmail.com>"]

[dependencies]
astro = "2.0.0"
cargo-web = "0.6.10"
stdweb = "0.4.4"
serde = "1.0.45"
serde_derive = "1.0.45"
serde_json = "1.0.17"
